### Creating Arrays

In [1]:
import numpy as np
a = np.array([2,3,4])                #Ensure to type within square brackets
print(a)
print(a.dtype)
b = np.array([1.2, 3.5, 5.1])
print(b)
print(b.dtype)

[2 3 4]
int32
[1.2 3.5 5.1]
float64


###### The type of the array can also be explicitly specified at creation time:

In [2]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


###### For elements of an array are originally unknown, but its size is known:
The function zeros creates an array full of zeros, the function ones creates an array full of ones,
and the function empty creates an array whose initial content is random and depends on the state of the memory.
By default, the dtype of the created array is float64

In [3]:
a = np.zeros( (3,4) )
b = np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified (two stacked 2-D arrays)
c = np.empty( (2,3) )                                 # uninitialized, output may vary
print (a)
print (b)
print (c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[ 9.44584894e+197  1.20345262e-306 -7.45642339e+016]
 [ 9.29232282e+197  1.24344475e-306  2.29330409e-094]]


###### Creating sequences of numbers

In [4]:
a = np.arange( 10, 30, 5 )
print (a)
b = np.arange( 0, 2, 0.3 )                 # it accepts float arguments (0.3 is the step)
print (b)
c = np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2
print (c)

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### Printing Arrays

In [5]:
a = np.arange(6)                         # 1-D array
print (a)
b = np.arange(12).reshape(4,3)           # 2-D array
print (b)
c = np.arange(24).reshape(2,3,4)         # 3-D array
print (c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Basic Operations

In [6]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a-b
print (c)
print (b**2)
print (10*np.sin(c))
print (a<35)

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -6.63633884  2.96368579  1.23573123]
[ True  True False False]


###### Multiplication

In [7]:
A = np.array( [[1,1],
              [0,1]] )
B = np.array( [[2,0],
              [3,4]] )
print (A*B)                         # elementwise product
print (A.dot(B))                    # matrix product
print (np.dot(A, B))                # same as above

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


###### Upcasting

In [8]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,np.pi,3)
print (b.dtype.name)
c = a+b
print (c.dtype.name)
d = np.exp(c*1j)
print (d.dtype.name)               #float upcasted to complex

float64
float64
complex128


###### Unary Operations

In [9]:
a = np.random.random((2,3))
print (a)
print (a.sum())
print (a.min())
print (a.max())

[[0.02668141 0.06273686 0.22775358]
 [0.47757606 0.15936433 0.54746358]]
1.5015758285880798
0.02668141346621722
0.5474635826171138


In [10]:
b = np.arange(12).reshape(3,4)
print (b)
print (b.sum(axis=0))                            # sum of each column
print (b.min(axis=1))                            # min of each row
print (b.cumsum(axis=1))                         # cumulative sum along each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


### Indexing, Slicing and Iterating

In [11]:
a = np.arange(10)**3
print (a)
print (a[2])
print (a[2:5])
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print (a)

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]


###### Multi-dimensional Arrays

In [12]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
print (b)
print (b[2,3])
print (b[0:5, 1])                       # each row in the second column of b
print (b[1:3, : ])                      # each column in the second and third row of b

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]


### Shape Manipulation
All return a modified array, but do not change the original array:

In [13]:
a = np.floor(10*np.random.random((3,4)))
print (a)
print (a.shape)
print(a.ravel())        # returns the array, flattened
print (a.reshape(6,2))  # returns the array with a modified shape
print (a.T)             # returns the array, transposed
print (a.T.shape)
print (a)               # un-modified 'a'

[[3. 9. 2. 5.]
 [0. 5. 3. 0.]
 [6. 7. 9. 3.]]
(3, 4)
[3. 9. 2. 5. 0. 5. 3. 0. 6. 7. 9. 3.]
[[3. 9.]
 [2. 5.]
 [0. 5.]
 [3. 0.]
 [6. 7.]
 [9. 3.]]
[[3. 0. 6.]
 [9. 5. 7.]
 [2. 3. 9.]
 [5. 0. 3.]]
(4, 3)
[[3. 9. 2. 5.]
 [0. 5. 3. 0.]
 [6. 7. 9. 3.]]


###### The 'reshape' function returns its argument with a modified shape, whereas the 'ndarray.resize' method modifies the array itself:

In [14]:
print (a)
a.resize((2,6))
print (a)               # modified 'a'

[[3. 9. 2. 5.]
 [0. 5. 3. 0.]
 [6. 7. 9. 3.]]
[[3. 9. 2. 5. 0. 5.]
 [3. 0. 6. 7. 9. 3.]]


### Distributions

###### Binomial Distribution

In [15]:
import numpy as np
n, p = 10, .5  # number of trials, probability of each trial
s = np.random.binomial(n, p, 1000)
print (s)

[6 4 4 6 4 6 7 3 6 7 4 5 6 5 6 5 4 8 5 5 4 6 4 4 4 6 7 5 4 6 3 8 3 5 3 5 7
 6 5 8 3 6 6 5 2 4 5 7 5 4 4 5 5 4 5 8 5 6 5 5 3 6 6 4 7 6 6 8 3 4 4 6 6 5
 4 8 5 5 7 5 3 7 6 6 1 8 2 6 4 7 4 4 4 2 5 4 4 3 6 5 6 5 2 5 8 5 4 4 7 3 6
 8 6 1 6 3 5 3 6 6 6 3 7 5 3 5 8 3 4 3 5 7 3 5 7 2 6 4 7 4 8 6 8 6 5 4 3 6
 8 4 7 7 6 2 6 4 7 4 6 9 5 4 5 8 7 4 5 8 6 1 7 7 6 6 3 6 7 6 7 2 4 6 2 7 2
 1 4 5 4 4 4 3 5 7 4 1 6 6 5 5 5 5 6 3 6 7 5 6 7 5 5 2 4 7 5 4 5 5 7 6 4 2
 5 6 3 5 7 4 6 6 5 3 5 5 4 5 5 7 7 4 6 6 3 6 6 5 6 3 5 4 6 7 5 6 5 4 8 5 5
 7 4 6 6 4 4 3 6 8 7 6 6 5 3 5 3 7 5 7 5 5 3 4 5 5 5 3 4 4 4 4 6 3 7 4 4 5
 5 7 4 5 7 6 4 6 5 7 3 3 5 8 6 5 4 5 4 3 6 7 5 2 4 6 4 4 6 1 5 3 3 7 5 3 5
 5 5 6 2 7 6 6 3 4 5 3 6 6 5 5 8 7 6 6 6 5 5 4 2 1 4 6 2 6 5 7 3 3 4 4 5 6
 6 4 6 2 4 4 4 4 4 4 6 4 7 6 7 4 2 4 4 6 7 5 5 7 4 3 7 6 5 7 4 5 3 5 6 5 5
 4 5 3 5 5 4 4 4 6 4 8 5 7 9 8 5 7 4 8 8 5 5 7 4 8 4 4 7 3 7 4 9 8 5 3 3 4
 3 6 4 4 4 5 3 6 6 6 6 4 7 4 4 4 7 5 4 4 6 6 6 2 7 6 4 5 4 5 2 4 5 5 6 5 6
 6 4 1 4 5 6 7 5 7 4 7 5 

###### Gamma Distribution

In [16]:
import numpy as np
shape, scale = 2., 2.  # mean=4, std=2*sqrt(2)
s = np.random.gamma(shape, scale, 1000)
print (s)

[ 8.54622796  2.06940175  7.61339865  9.49699949  2.0888688   2.38933489
 12.71406177  7.1082248   4.44724746  0.55954259  3.72643058  2.98230947
  6.2939551   2.99013539  7.08060145  2.85017836  3.78481573  4.92279514
  9.36271428  2.93091259  2.4997747   3.4782429   2.06871371  2.8877997
  7.79215023  1.85451809  5.06681748  3.44037501  4.92150193  8.36109356
  2.67784661  1.25734261  5.95146717  2.20970316  5.62534593  1.94581655
  7.11202003  3.75032336  1.36323197  6.82327146 10.90940837  5.46657856
  5.06882425  4.91965348  0.50134533  5.76806877  7.11970918  5.18885591
  3.43928483  7.41967302 15.41642849  3.01885539  0.29938203  2.94889193
  3.3678014   0.74955937  1.28872841  9.73469771  8.72287049  3.88964456
  8.79077268  8.02411339  7.36082346  1.34264996  2.99540642  1.64611554
  2.23017545  1.65317193  4.98892075  3.3035542   1.17181691  0.90102424
  1.88541681  3.77819613  3.26881777  2.83133258  3.52066123  0.81543009
  4.33544519  0.29361307  7.62487913  1.04113329  2.

###### Laplace Distribution

In [17]:
import numpy as np
loc, scale = 0., 1.
s = np.random.laplace(loc, scale, 1000)
print (s)

[ 1.30674707e+00  3.22738855e+00  2.62812451e-01 -1.08237824e-01
 -4.97071194e-01  9.18436645e-01  9.15917760e-01 -1.83108685e+00
 -2.46300169e+00  5.87430669e-01 -2.14103181e+00  8.92716810e-01
 -4.68168738e-01 -3.59553690e-01 -5.71536042e-01  1.18440856e-01
  2.44380566e-01 -1.31405926e-02  2.68460268e+00 -8.74262476e-01
 -3.47970102e+00  8.39847008e-01 -1.26260239e-01  2.96284173e+00
  4.23319394e-01 -7.37366269e-02  8.92551437e-01 -2.74423406e+00
 -3.75397887e-01  3.58266394e-01  4.38117721e-01  2.74847187e-01
  2.08273475e+00 -6.11609484e-01 -1.11312582e+00 -6.20677563e-01
 -2.64868936e+00 -3.98976487e-02  4.58227871e-01 -3.60609748e-01
 -5.60863580e+00  8.62477559e-01  2.43375489e+00  4.56859557e-01
  4.51515707e+00 -3.67786746e+00 -1.26161510e+00 -7.73811443e-01
  2.13037464e+00  2.84042648e-02  2.99047334e-01 -2.33021593e+00
  1.48626829e+00  1.18972672e+00 -9.40256337e-01  1.92271712e-01
 -3.94806423e-01 -2.29008361e+00 -5.83633047e+00 -1.07107308e+00
  1.40653432e+00 -1.95650

###### Poisson Distribution

In [18]:
import numpy as np
lam, size = 5,10000
s = np.random.poisson(lam, size)
print (s)

[4 2 6 ... 4 5 4]


### References
https://docs.scipy.org/doc/numpy-1.14.0/reference/